# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    OF.UserBundle.profile.form.type:
        class: OF\UserBundle\Form\Type\ProfileFormType
        tags:
            - { name: form.type, alias: OF.UserBundle.profiletype}