of_calendar_homepage:
    path:     /calendar
    defaults: { _controller: OFCalendarBundle:Calendar:show }

of_calendar_usersadmin:
    path:     /adminpanel/users
    defaults:
        _controller: OFCalendarBundle:Admin:usersAdmin

of_calendar_Supprusers:
    path:     /adminpanel/supprUsers/{id}
    defaults:
        _controller: OFCalendarBundle:Admin:supprUserAdmin

of_calendar_Modifusers:
    path:     /adminpanel/modifUsers/{id}
    defaults:
        _controller: OFCalendarBundle:Admin:modifUserAdmin

of_calendar_admin:
    path:     /adminpanel
    defaults:
        _controller: OFCalendarBundle:Admin:homeAdmin

of_calendar_ajoutUserEvent:
    path:     /visite/{id}/ajoutUser
    defaults:
        _controller: OFCalendarBundle:Visite:ajoutUser
    methods: [post]

of_calendar_showModalEvent:
    path:     /calendar/show
    defaults:
        _controller: OFCalendarBundle:Visite:viewModal
    methods: [post]

of_calendar_supprUserEvent:
    path:     /visite/{id}/supprUser
    defaults:
        _controller: OFCalendarBundle:Visite:supprUser
    methods: [post]

of_calendar_validerEtapeEvent:
    path:     /visite/{id}/valider/{etape}
    defaults:
        _controller: OFCalendarBundle:Visite:validerEtape
    methods: [post]

of_calendar_demandeEtapeEvent:
    path:     /visite/{id}/validreq/{etape}
    defaults:
        _controller: OFCalendarBundle:Visite:miseenvalidationEtape
    methods: [post]
    
of_calendar_evnoyerMail:
    path:     /visite/{id}/sendMail/{etape}
    defaults:
        _controller: OFCalendarBundle:Visite:envoyerMail

of_calendar_view_visite:
    path:     /visite/{id}/{etape}
    defaults:
        _controller: OFCalendarBundle:Visite:view
        etape: 0
    options:
        expose: true

