of_calendar_homepage:
    path:     /
    defaults: { _controller: OFCalendarBundle:Calendar:show }




of_calendar_statsAdmin: 
    path:     /admin/
    defaults:
        _controller: OFCalendarBundle:Visite:statsAll




of_calendar_usersadmin:
    path:     /adminpanel/users
    defaults:
        _controller: OFCalendarBundle:Admin:usersAdmin

of_calendar_Supprusers:
    path:     /adminpanel/supprUsers/{id}
    defaults:
        _controller: OFCalendarBundle:Admin:supprUserAdmin

of_calendar_AdminViewVisiteuser:
    path:     /adminpanel/viewVisiteUser/{id}
    defaults:
        _controller: OFCalendarBundle:Admin:viewVisiteUserAdmin

of_calendar_Modifusers:
    path:     /adminpanel/modifUsers/{id}
    defaults:
        _controller: OFCalendarBundle:Admin:modifUserAdmin
of_calendar_ajoutUserEvent:
    path:     /visite/{id}/ajoutUser
    defaults:
        _controller: OFCalendarBundle:Visite:ajoutUser
    methods: [post]


of_calendar_supprUserEvent:
    path:     /visite/{id}/supprUser
    defaults:
        _controller: OFCalendarBundle:Visite:supprUser
    methods: [post]







of_calendar_visitesadmin:
    path:     /adminpanel/visites
    defaults:
        _controller: OFCalendarBundle:Admin:visitesAdmin

of_calendar_Supprvisites:
    path:     /adminpanel/supprVisites/{id}
    defaults:
        _controller: OFCalendarBundle:Admin:supprVisiteAdmin

of_calendar_Modifclients:
    path:     /adminpanel/modifClients/{id}
    defaults:
        _controller: OFCalendarBundle:Admin:modifClientAdmin
of_calendar_ajoutClientEvent:
    path:     /visite/{id}/ajoutClient
    defaults:
        _controller: OFCalendarBundle:Visite:ajoutClient
    methods: [post]




of_calendar_documentsadmin:
    path:     /adminpanel/documents
    defaults:
        _controller: OFCalendarBundle:Admin:documentsAdmin

of_calendar_Supprdocuments:
    path:     /adminpanel/supprDocuments/{id}
    defaults:
        _controller: OFCalendarBundle:Admin:supprDocumentAdmin

of_calendar_Modifdocuments:
    path:     /adminpanel/modifDocuments/{id}
    defaults:
        _controller: OFCalendarBundle:Admin:modifDocumentAdmin

of_calendar_voirDocuments:
    path:     /voirDocuments
    defaults:
        _controller: OFCalendarBundle:Document:view






of_calendar_validerEtapeEvent:
    path:     /visite/{id}/valider/{etape}
    defaults:
        _controller: OFCalendarBundle:Visite:validerEtape
    methods: [post]

of_calendar_demandeEtapeEvent:
    path:     /visite/{id}/validreq/{etape}
    defaults:
        _controller: OFCalendarBundle:Visite:miseenvalidationEtape
    methods: [post]
    
of_calendar_evnoyerMail:
    path:     /visite/{id}/sendMail/{etape}
    defaults:
        _controller: OFCalendarBundle:Visite:envoyerMail

of_calendar_view_visite:
    path:     /visite/{id}/{etape}
    defaults:
        _controller: OFCalendarBundle:Visite:view
        etape: 0
    options:
        expose: true

of_calendar_showModalEvent:
    path:     /calendar/show
    defaults:
        _controller: OFCalendarBundle:Visite:viewModal
    methods: [post]


of_calendar_qualipanel:
    path:     /quali
    defaults:
        _controller: OFCalendarBundle:Visite:showQualiteVisites

of_calendar_view_qualitevisite:
    path:     /quali/visite/{id}
    defaults:
        _controller: OFCalendarBundle:Visite:showQualiteVisite
    options:
        expose: true
of_calendar_qualimaj:
    path:     /quali/maj
    defaults:
        _controller: OFCalendarBundle:Visite:majVisite
    
of_calendar_voirQuestionnaire:
    path:     /questionnaire/{id}
    defaults:
        _controller: OFCalendarBundle:Visite:showQuestionnaireHTML








of_calendar_voirDocVisite:
    path:     /recap/{id}
    defaults:
        _controller: OFCalendarBundle:Visite:showrecapHTML



of_calendar_panelUser:
    path:     /panelUser/
    defaults:
        _controller: OFCalendarBundle:Visite:showVisites